apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: quoteapi
  name: quoteapi
  namespace: <PROJECT>
spec:
  host: <DOMAIN>
  port:
    targetPort: 8001-tcp
  to:
    kind: Service
    name: quoteapi
    weight: 100
  wildcardPolicy: None
