apiVersion: v1
kind: Service
metadata:
  labels:
    app: quoteapi
  name: quoteapi
  namespace: <PROJECT>
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: quoteapi
  type: ClusterIP
