apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: geocoder
  namespace: earthquake-demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/gswk/geocoder:flood-debug
            env:
            - name: DB_HOST
              value: "postgresql-95-rhel7.earthquake-demo.svc.cluster.local"
            - name: DB_DATABASE
              value: "geocodedb"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "admin"
