spring:
  profiles: ocp 
  cloud:
    stream:
      bindings:     
        cargoHandlingChannel1:
          destination: cargoHandlings1
          group: cargoHandlingsQueue1
        cargoHandlingChannel2:
          destination: cargoHandlings2
          group: cargoHandlingsQueue2         
  datasource:
    url: "jdbc:mysql://mysql:3306/handlingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: handlingmsdb
    password: handlingmsdb
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: handling        

server:
  port: 8004
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev
---
spring:
  profiles:
    active: local 
  cloud:
    stream:
      bindings:     
        cargoHandlingChannel:
          destination: cargoHandlings
          group: cargoHandlingsQueue
  datasource:
    url: "jdbc:mysql://localhost:3306/handlingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: handlingmsdb
    password: handlingmsdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: handling        

server:
  port: 8004
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev  