apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cargotracker
  name: cargotracker
  namespace: <PROJECT>
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: <CONTAINER>
  tags:
  - items:
    tag: latest