apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: booking
  name: booking
  namespace: <PROJECT>
spec:
  output:
    to:
      kind: ImageStreamTag
      name: booking:latest
  runPolicy: Serial
  source:
    contextDir: microservices/cargotracker/spring-boot/booking
    git:
      ref: master
      uri: <GITHUBREPO>
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./deployment/Dockerfile
    type: Source