apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: booking
  name: booking
  namespace: <PROJECT>
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: <CONTAINER>
  tags:
  - items:
    tag: latest