spring:
  profiles: ocp
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: "jdbc:mysql://mysql.cargotracker:3306/trackingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: trackingmsdb
    password: trackingmsdb
  application:
    name: tracking        

server:
  port: 8084
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  metrics:
    tags:
      application: ${spring.application.name}
      environment: test
---
spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: "jdbc:mysql://localhost:3306/trackingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: trackingmsdb
    password: trackingmsdb
  application:
    name: tracking        

server:
  port: 8084
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev