spring:
  profiles: ocp
  datasource:
    url: "jdbc:mysql://mysql:3306/routingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: routingmsdb
    password: routingmsdb
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: routing        

server:
  port: 8003
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev
---
spring:
  profiles:
    active: local
  datasource:
    url: "jdbc:mysql://localhost:3306/routingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: routingmsdb
    password: routingmsdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: routing        

server:
  port: 8003
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev       