apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: booking
  namespace: booking
  labels:
    app: booking
spec:
  replicas: 1
  strategy: 
    type: Recreate  
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - image: arunimi/booking:1.0.0
        name: booking
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "ocp"
        readinessProbe:
          httpGet:
            path: /actuator
            port: 8001
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8001
          initialDelaySeconds: 60
          timeoutSeconds: 10          
        resources:         
          requests:
            cpu: 20m
            memory: 50Mi      
---
apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: booking
  labels:
    app: booking
spec:
  type: ClusterIP
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    app: booking
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: booking
  name: booking
  namespace: booking
spec:
  host: booking.apps.eu-3.os.fyre.ibm.com
  subdomain: ""
  tls:
    termination: passthrough
  to:
    kind: Service
    name: booking
    weight: 100
  wildcardPolicy: None
