apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: booking
  name: booking
  namespace: <PROJECT>
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: <CONTAINER>
  tags:
  - items:
    tag: latest
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: booking
  name: booking
  namespace: <PROJECT>
spec:
  output:
    to:
      kind: ImageStreamTag
      name: booking:latest
  runPolicy: Serial
  source:
    contextDir: microservices/cargotracker/spring-boot
    git:
      ref: master
      uri: <GITHUBREPO>
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./deployment/Dockerfile
    type: Source
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: booking
  name: booking
  namespace: <PROJECT>
spec:
  replicas: 1
  selector:
    deploymentconfig: booking
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: booking
        deploymentconfig: booking       
    spec:
      containers:
      - image: <CONTAINER>
        imagePullPolicy: Always
        name: booking
        ports:
        - containerPort: 8001
          protocol: TCP
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - booking
      from:
        kind: ImageStreamTag
        name: booking:latest
        namespace: <PROJECT>
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: booking
  labels:
    app: booking
spec:
  type: ClusterIP
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    app: booking
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: booking
  name: booking
  namespace: booking
spec:
  host: booking-booking.apps.eu-3.os.fyre.ibm.com
  port:
    targetPort: 8001
  subdomain: ""
  to:
    kind: Service
    name: booking
    weight: 100
  wildcardPolicy: None