apiVersion: apps/v1
kind: Deployment
metadata:
  name: divide
  namespace: <PROJECT>
  labels:
    app: divide
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divide
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: divide
        version: v1
    spec:
      containers:
      - name: divide
        image: <CONTAINER>
